spring.application.name=managementsystem

#Server configuration
server.port=8089
spring.mvc.format.date=YYYY-MM-DD

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/management_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=


### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
### logging configuration ###
logging.level.root=info
# Logging pattern for the console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level- %logger{45} - %msg %n

secreteJwtString=Sunshine!2025$SkyBlueSunshine!2025$SkyBlue



